"""Report page — Full alert log synced with map's live weather state."""

from datetime import datetime, timedelta

import pandas as pd
import streamlit as st

from core.db import get_alerts
from core.weather_client import city_has_active_rain


def _caption(msg):
    st.markdown(
        f"<p style='color:#B0B3B8 !important;font-size:13px;'>{msg}</p>",
        unsafe_allow_html=True,
    )


def _subheader(msg):
    st.markdown(
        f"<h3 style='color:#E4E6EB !important;'>{msg}</h3>",
        unsafe_allow_html=True,
    )


def _info_box(msg):
    st.markdown(
        f"<div style='background:#1E2A3A;border:1px solid #2D4F6A;border-radius:8px;"
        f"padding:10px 14px;margin:8px 0;color:#B0D4F1 !important;'>{msg}</div>",
        unsafe_allow_html=True,
    )


def _success_box(msg):
    st.markdown(
        f"<div style='background:#1B3A2D;border:1px solid #2D6A4F;border-radius:8px;"
        f"padding:10px 14px;margin:8px 0;color:#6FCF97 !important;'>{msg}</div>",
        unsafe_allow_html=True,
    )


def _err_box(msg):
    st.markdown(
        f"<div style='background:#3D1F1F;border:1px solid #A94442;border-radius:8px;"
        f"padding:10px 14px;margin:8px 0;color:#F5B7B1 !important;'>{msg}</div>",
        unsafe_allow_html=True,
    )


def render():
    live_rain = city_has_active_rain()

    st.markdown(
        "<h1 style='color:#FAFAFA !important;'>\U0001F4CB Report \u2014 Full Alert Log</h1>",
        unsafe_allow_html=True,
    )
    _caption("Complete record of all flood risk alerts generated by the system")

    today = datetime.now().date()
    default_from = today - timedelta(days=30)

    col1, col2, col3 = st.columns(3)
    with col1:
        from_date = st.date_input("From Date", value=default_from)
    with col2:
        to_date = st.date_input("To Date", value=today)
    with col3:
        risk_filter = st.selectbox(
            "Risk Level", options=["All", "critical", "high", "moderate", "low"], index=0
        )

    try:
        alerts = get_alerts(
            start_date=from_date.strftime("%Y-%m-%d"),
            end_date=to_date.strftime("%Y-%m-%d"),
            risk_level=None if risk_filter == "All" else risk_filter,
        )
    except Exception as e:
        _err_box("Failed to fetch alerts: " + str(e))
        alerts = []

    if not live_rain:
        _success_box("\u2705 Weather is stable. No critical flood areas detected at the moment.")

    total = len(alerts)
    critical_count = sum(1 for a in alerts if a.get("risk_level") == "critical")
    high_count = sum(1 for a in alerts if a.get("risk_level") == "high")
    resolved_count = sum(1 for a in alerts if a.get("resolved", 0) == 1)

    col_a, col_b, col_c, col_d = st.columns(4)
    col_a.metric("Total Alerts (in range)", total)
    col_b.metric("Critical", critical_count)
    col_c.metric("High", high_count)
    col_d.metric("Resolved", f"{resolved_count}/{total}")

    if not alerts:
        _info_box("No alerts found for the selected filters.")
        return

    rows = []
    for a in alerts:
        rows.append(
            {
                "Timestamp": a.get("alert_timestamp", "\u2014"),
                "Latitude": a.get("latitude"),
                "Longitude": a.get("longitude"),
                "Street": a.get("street_name", "\u2014"),
                "Risk Score": a.get("risk_score"),
                "Risk Level": a.get("risk_level", "low").upper(),
                "Rainfall (mm)": a.get("rainfall_mm") if a.get("rainfall_mm") is not None else "\u2014",
                "Water Detected": "Yes" if a.get("water_detected") else "No",
                "Decision Source": a.get("decision_source", "\u2014"),
                "Traffic Disruption": "Yes" if a.get("traffic_disruption_predicted") else "No",
                "Resolved": "Yes" if a.get("resolved", 0) == 1 else "No",
            }
        )

    df = pd.DataFrame(rows)
    st.dataframe(df, use_container_width=True, height=500)

    csv = df.to_csv(index=False)
    date_str = f"{from_date}_{to_date}"
    st.download_button(
        "\U0001F4E5 Download as CSV",
        data=csv,
        file_name=f"hail_flood_alerts_{date_str}.csv",
        mime="text/csv",
    )

    _subheader("Risk Level Distribution")
    counts = df["Risk Level"].value_counts()
    st.bar_chart(counts)
